"""Add today and thru columns to MasterScore

Revision ID: 2b01135010ea
Revises: 
Create Date: 2025-04-11 14:34:32.641470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b01135010ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('today', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('thru', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_score', schema=None) as batch_op:
        batch_op.drop_column('thru')
        batch_op.drop_column('today')

    # ### end Alembic commands ###
